server:
  port: 18888
service:
  author: nanchengcao


# springboot 2.1.6 引入actuator需要声明导出的接口，否则不会像早期版本那样自动映射出去
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web: TRACE
eureka:
  #instance:
  #  hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    #service-url:
    #  defaultZong: http://${eureka.instance.hostname}:18887/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
# 访问地址：http://localhost:18888/
spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: eureka